config/routes.rb
Nofaffbudget::Application.routes.draw do
  resources :companies

  resources :weekly_budgets do
    resources :transactions
  end

  resources :budgets do
    resources :categories
  end
  

  resources :budgets do
    resources :weekly_budgets 
  end

  root :to => 'home#index'

end

app/models/weekly_budget.rb
class WeeklyBudget < ActiveRecord::Base
  attr_accessible :budget_id, :current_fund, :start_fund, :weekno, :end_date, :start_date

  belongs_to :budget
  has_many :transactions
  

end

app/controllers/weekly_budgets_controller.rb
class WeeklyBudgetsController < ApplicationController
  # GET /weekly_budgets
  # GET /weekly_budgets.json
  def index
    if params[:budget_id].nil?
      @weekly_budgets = WeeklyBudget.all
    else

      @budget = Budget.find(params[:budget_id])
      @weekly_budgets = @budget.weekly_budgets.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @weekly_budgets }
    end
  end

  # GET /weekly_budgets/1
  # GET /weekly_budgets/1.json
  def show
    if params[:budget_id].nil?
        @weekly_budget = WeeklyBudget.find(params[:id])
    else

      @budget = Budget.find(params[:budget_id])
      @weekly_budget = @budget.weekly_budgets.find(params[:id])
     end



    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @weekly_budget }
    end
  end

  # GET /weekly_budgets/new
  # GET /weekly_budgets/new.json
  def new
    if params[:budget_id].nil?
           @weekly_budget = WeeklyBudget.find(params[:id])

    else

      @budget = Budget.find(params[:budget_id])
 
      @weekly_budget = WeeklyBudget.new
    end


    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @weekly_budget }
    end
  end

  # GET /weekly_budgets/1/edit
  def edit
    if params[:budget_id].nil?
           @weekly_budget = WeeklyBudget.find(params[:id])

    else

    @budget = Budget.find(params[:budget_id])
    @weekly_budget = @budget.weekly_budgets.find(params[:id])
  end

  end

  # POST /weekly_budgets
  # POST /weekly_budgets.json
  def create
  if params[:budget_id].nil?
         @weekly_budget = WeeklyBudget.find(params[:id])
 
  else


      @budget = Budget.find(params[:budget_id])
      @weekly_budget = @budget.weekly_budgets.new(params[:weekly_budget])
  end


    respond_to do |format|
      if @weekly_budget.save
        if params[:budget_id].nil?
             format.html { redirect_to @weekly_budget, notice: 'Weekly budget was successfully created.' }
          format.json { render json: @weekly_budget, status: :created, location: @weekly_budget }
        else
           format.html { redirect_to budget_weekly_budget_path(@budget,@weekly_budget), notice: 'Weekly budget was successfully created.' }
          format.json { render json: @weekly_budget, status: :created, location: @weekly_budget }

        end

      else
        format.html { render action: "new" }
        format.json { render json: @weekly_budget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /weekly_budgets/1
  # PUT /weekly_budgets/1.json
  def update
       if params[:budget_id].nil?
             @weekly_budget = WeeklyBudget.find(params[:id])

       else

      @budget = Budget.find(params[:budget_id])
      @weekly_budget = @budget.weekly_budgets.find(params[:id])
    end

    


    respond_to do |format|
      if @weekly_budget.update_attributes(params[:weekly_budget])
        if params[:budget_id].nil?
          format.html { redirect_to @weekly_budget, notice: 'Weekly budget was successfully updated.' }
          format.json { head :no_content }
        else
           format.html { redirect_to budget_weekly_budget_path(@budget,@weekly_budget), notice: 'Weekly budget was successfully updated.' }
          format.json { head :no_content }
        end
      else
        format.html { render action: "edit" }
        format.json { render json: @weekly_budget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weekly_budgets/1
  # DELETE /weekly_budgets/1.json
  def destroy
       if params[:budget_id].nil?
     @weekly_budget = WeeklyBudget.find(params[:id])

      else

        @budget = Budget.find(params[:budget_id])
        @weekly_budget = @budget.weekly_budgets.find(params[:id])
      end

     

        @weekly_budget.destroy

    respond_to do |format|
    if params[:budget_id].nil?
      format.html { redirect_to weekly_budgets_url }
      format.json { head :no_content }
    else
      format.html { redirect_to budget_weekly_budgets_url }
      format.json { head :no_content }
    end

    end
  end



end

app/helpers/weekly_budgets_helper.rb
module WeeklyBudgetsHelper
end

app/views/weekly_budgets/_form.html.erb
<%= form_for([@budget, @weekly_budget]) do |f| %>

    <% if @weekly_budget.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@weekly_budget.errors.count, "error") %> prohibited this weekly_budget from being saved:</h2>

        <ul>
        <% @weekly_budget.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

  <div class="field">
    <%= f.label :weekno %><br />
    <%= f.number_field :weekno %>
  </div>

  <div class="field">
    <%= f.label :start_fund %><br />
    <%= f.text_field :start_fund %>
  </div>
  <div class="field">
    <%= f.label :current_fund %><br />
    <%= f.text_field :current_fund %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/weekly_budgets/edit.html.erb
<h1>Editing weekly_budget</h1>

<%= render 'form' %>

<%= link_to 'Show', budget_weekly_budget_path(@budget, @weekly_budget) %> |
<%= link_to 'Back', budget_weekly_budgets_path(@budget) %>

app/views/weekly_budgets/index.html.erb
<h1>Listing weekly_budgets</h1>

<table>
  <tr>
    <th>Weekno</th>
    <th>Budget</th>
    <th>Start fund</th>
    <th>Current fund</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @weekly_budgets.each do |weekly_budget| %>
  <tr>
    <td><%= weekly_budget.weekno %></td>
    <td><%= weekly_budget.budget_id %></td>
    <td><%= weekly_budget.start_fund %></td>
    <td><%= weekly_budget.current_fund %></td>
    <% if @budget==999 %>

      <td><%= link_to 'Show', budget_weekly_budget_path(@budget) %></td>
      <td><%= link_to 'Edit', edit_weekly_budget_path(weekly_budget) %></td>
      <td><%= link_to 'Destroy', weekly_budget, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% else %>
        <td><%= link_to 'Show', budget_weekly_budget_path(@budget, weekly_budget) %></td>
        <td><%= link_to 'Edit', edit_budget_weekly_budget_path(@budget, weekly_budget) %></td>
        <td><%= link_to 'Destroy', [@budget,weekly_budget], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
<% end %>
</table>

<br />
<% if @budget == 999 %>
 <%= link_to 'New Weekly budget', new_weekly_budget_path %>
 
<% else %>
 <%= link_to 'New Weekly budget', new_budget_weekly_budget_path(@budget) %>

<% end %>

app/views/weekly_budgets/new.html.erb
<h1>New weekly_budget</h1>

<%= render 'form' %>

<%= link_to 'Back', budget_weekly_budgets_path(@budget) %>

app/views/weekly_budgets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Weekno:</b>
  <%= @weekly_budget.weekno %>
</p>

<p>
  <b>Budget:</b>
  <%= @weekly_budget.budget_id %>
</p>

<p>
  <b>Start fund:</b>
  <%= @weekly_budget.start_fund %>
</p>

<p>
  <b>Current fund:</b>
  <%= @weekly_budget.current_fund %>
</p>

<% if @budget.nil? %>
    <%= link_to 'Edit', edit_weekly_budget_path(@weekly_budget) %> |
    <%= link_to 'Back', weekly_budgets_path %>
<%else%>

    <%= link_to 'Edit', edit_budget_weekly_budget_path(@budget, @weekly_budget) %> |
    <%= link_to 'Back', budget_weekly_budgets_path(@budget) %>
  <% end %>