config/routes.rb
Nofaffbudget::Application.routes.draw do
  resources :companies

  resources :weekly_budgets do
    resources :transactions
  end

  resources :budgets do
    resources :categories
  end
  

  resources :budgets do
    resources :weekly_budgets 
  end

  root :to => 'home#index'

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  # GET /transactions
  # GET /transactions.json
  def index
    @weekly_budget = WeeklyBudget.find(params[:weekly_budget_id])
      @transactions = @weekly_budget.transactions.all
       budget_id = @weekly_budget.budget_id
        @categories = Category.where(budget_id: budget_id)

      @transactions = @weekly_budget.transactions.all

          @category_hash = []

          @categories.each do |c|
            sum_value = 0.0
            @transactions.each do |t|
              if t.category_id == c.id
                sum_value = sum_value + t.amount.to_f
              end
            end
            @category_hash << sum_value.round(2)
          end
          puts @category_hash

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: {:transactions=>@transactions, :amounts=>@category_hash} }
    end
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
    @weekly_budget = WeeklyBudget.find(params[:weekly_budget_id])

    @transaction =@weekly_budget.transactions.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @transaction }
    end
  end

  # GET /transactions/new
  # GET /transactions/new.json
  def new
    @weekly_budget = WeeklyBudget.find(params[:weekly_budget_id])
    @transaction = Transaction.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @transaction }
    end
  end

  # GET /transactions/1/edit
  def edit
    @weekly_budget = WeeklyBudget.find(params[:weekly_budget_id])
    @transaction = @weekly_budget.transactions.find(params[:id])
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @weekly_budget = WeeklyBudget.find(params[:weekly_budget_id])
    @transaction = @weekly_budget.transactions.new(params[:transaction])

    new_current_fund = @weekly_budget.current_fund - @transaction.amount

    weekly_budget_update = {}
    weekly_budget_update[:weekly_budget] = {}
    weekly_budget_update[:weekly_budget][:current_fund] = new_current_fund.round(2)
    weekly_budget_update.to_json


    respond_to do |format|
      if @transaction.save
          @weekly_budget.update_attributes(weekly_budget_update[:weekly_budget])
        format.html { redirect_to weekly_budget_transaction_path(@weekly_budget, @transaction), notice: 'Transaction was successfully created.' }
        format.json { render json: @transaction, status: :created, location: weekly_budget_transaction_path(@weekly_budget, @transaction) }
      else
        format.html { render action: "new" }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /transactions/1
  # PUT /transactions/1.json
  def update
    @weekly_budget = WeeklyBudget.find(params[:weekly_budget_id])

    @transaction = @weekly_budget.transactions.find(params[:id])

    respond_to do |format|
      if @transaction.update_attributes(params[:transaction])
        format.html { redirect_to weekly_budget_transaction_path(@weekly_budget, @transaction), notice: 'Transaction was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @weekly_budget = WeeklyBudget.find(params[:weekly_budget_id])

    @transaction = @weekly_budget.transactions.find(params[:id])
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to weekly_budget_transactions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= form_for([@weekly_budget, @transaction]) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category_id %><br />
    <%= f.collection_select :category_id, Category.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing transaction</h1>

<%= render 'form' %>

<%= link_to 'Show', [@weekly_budget, @transaction] %> |
<%= link_to 'Back', weekly_budget_transactions_path %>

app/views/transactions/index.html.erb
<h1>Listing transactions</h1>

<table>
  <tr>
    <th>Category</th>
    <th>Amount</th>
    <th>Weekly budget</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @transactions.each do |transaction| %>
  <tr>
    <td><%= transaction.category.name %></td>
    <td><%= transaction.amount %></td>
    <td><%= transaction.weekly_budget.weekno %></td>
    <td><%= link_to 'Show', weekly_budget_transaction_path(@weekly_budget, transaction) %></td>
    <td><%= link_to 'Edit', edit_weekly_budget_transaction_path(@weekly_budget, transaction) %></td>
    <td><%= link_to 'Destroy', [@weekly_budget, transaction], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Transaction', new_weekly_budget_transaction_path(@weekly_budget) %>

app/views/transactions/new.html.erb
<h1>New transaction</h1>

<%= render 'form' %>

<%= link_to 'Back', weekly_budget_transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Category:</b>
  <%= @transaction.category.name %>
</p>

<p>
  <b>Amount:</b>
  <%= @transaction.amount %>
</p>

<p>
  <b>Weekly budget:</b>
  <%= @transaction.weekly_budget.weekno %>
</p>


<%= link_to 'Edit', edit_weekly_budget_transaction_path(@weekly_budget, @transaction) %> |
<%= link_to 'Back', weekly_budget_transactions_path %>